import { TechCategory } from "@/types/portfolio";

export const TECH_PRESETS: Record<
  TechCategory,
  { label: string; items: string[] }
> = {
  Frontend: {
    label: "Frontend",
    items: [
      "HTML5",
      "CSS3",
      "JavaScript",
      "TypeScript",
      "React",
      "Next.js",
      "Vue",
      "Nuxt",
      "Svelte",
      "Solid.js",
      "Tailwind CSS",
      "Sass",
      "Redux",
      "Zustand",
      "Three.js",
      "Framer Motion",
    ],
  },
  Backend: {
    label: "Backend",
    items: [
      "Node.js",
      "Express",
      "NestJS",
      "Python",
      "Django",
      "FastAPI",
      "PHP",
      "Laravel",
      "Go",
      "Rust",
      "Java",
      "Spring Boot",
      "C#",
      ".NET",
      "PostgreSQL",
      "MongoDB",
      "Redis",
      "GraphQL",
    ],
  },
  "DevOps & Cloud": {
    label: "DevOps & Cloud",
    items: [
      "Docker",
      "Kubernetes",
      "AWS",
      "Cloudflare",
      "Cloudflare R2",
      "Vercel",
      "Netlify",
      "Supabase",
      "Firebase",
      "Nginx",
      "CI/CD",
      "Terraform",
      "Railway",
    ],
  },
  "AI & Machine Learning": {
    label: "AI & Machine Learning",
    items: [
      "OpenAI API",
      "Claude API",
      "LangChain",
      "PyTorch",
      "TensorFlow",
      "Hugging Face",
      "Ollama",
      "Cursor",
      "v0",
      "Midjourney",
      "Perplexity",
    ],
  },
  "Security & Identity": {
    label: "Security & Identity",
    items: [
      "Supabase Auth",
      "Clerk",
      "NextAuth.js / Auth.js",
      "Auth0",
      "JWT",
      "OAuth 2.0",
      "Kinde",
    ],
  },
  "CMS & No-Code": {
    label: "CMS & No-Code",
    items: [
      "Sanity",
      "Strapi",
      "WordPress",
      "Payload CMS",
      "Framer",
      "Webflow",
      "Notion API",
    ],
  },
  "Developer Tools": {
    label: "Developer Tools",
    items: [
      "Git",
      "GitHub",
      "VS Code",
      "Postman",
      "pnpm",
      "npm",
      "Turborepo",
      "ESLint",
      "Prettier",
      "Raycast",
    ],
  },
};